    
entero numero, suma 
inicio 
	escriba "Escriba el numero"
	lea numero
	escriba "Escriba la suma"
	lea suma
		mientras (numero <= 100) haga
			escriba suma
			llamar nueva_linea
			suma <-suma + numero 
			numero <-numero + 1 
				llamar nueva_linea 
				llamar color_fondo (11)
				llamar obtener_caracter
				escriba numero, " "
		fin mientras
			escriba "La suma total es", suma , numero
fin
		
