real a,b,c
inicio 
escriba "sumando dos numeros ingresados por teclado" 
llamar nueva_linea
escriba "ingrese el primer numero, puede ser entero o decimal " 
lea a 
escriba "ingrese el segundo numero, puede ser entero o decimal " 
lea b 
c <- a+b 
escriba "la suma de ", a," mas ",b," es= ",c
llamar nueva_linea 
escriba "la suma de a que es "  ,a, " mas b que es " ,b, " es = " ,c  
fin 
