entero i,j,suma
inicio



		suma <-0
		para  i<-0 hasta 8 haga
		escriba i
		llamar nueva_linea
		i<-i+1
		fin para
		llamar nueva_linea
		llamar nueva_linea
		escriba "ahora numeros pares "
		llamar nueva_linea
		para i<-0 hasta 8 haga
		escriba i
		llamar nueva_linea
		 i<-i+1
		 llamar nueva_linea
		 para j<-5 hasta 7 haga
		 escriba "noche "
		 llamar nueva_linea
		 fin para
		
		fin para 
		 
		 
	fin
		